/**
 * Deterministic Attention fixture queues.
 *
 * Explicit decision gates only — no existing normalized domain owns
 * approvals / policy exceptions, so they live here as fixture semantics.
 * Blocked work is never faked as an approval; snapshot derivation owns
 * blocked items from real execution state.
 */

import type { ScenarioId } from "../runtime/runtime-types";
import type { AttentionItem } from "./domain";
import type { AttentionQueue } from "./selectors";

const DECISION_AT = "2026-09-25T09:30:00Z";

function history(): AttentionItem[] {
  return [
    {
      id: "attention-history-spend-approved",
      kind: "budget",
      status: "approved",
      severity: "high",
      title: "Spend increase approved for ledger inspector",
      summary: "Raised the ledger Mission cap by $10 after cache review.",
      whatHappened: "A spend-increase request for the ledger inspector was approved.",
      whyNeeded: "Historical record — no action remains.",
      inactionConsequence: "None; the decision is recorded.",
      createdAt: "2026-09-24T14:00:00Z",
      updatedAt: "2026-09-24T15:10:00Z",
      source: "policy",
      destination: "resource-ledger",
      missionId: "mission-ledger",
      missionTitle: "Resource ledger inspector",
      approval: {
        id: "appr-history-spend",
        type: "spend-increase",
        requestedAction: "Raise the Mission spend cap by $10.",
        reason: "Cache-heavy verification kept running past the soft cap.",
        requester: "OCG policy gate",
        missionId: "mission-ledger",
        missionTitle: "Resource ledger inspector",
        requestedAt: "2026-09-24T14:00:00Z",
        estimatedImpact: "Ledger verification completes without a second gate.",
        requestedSpendMicros: 10_000_000,
        approveConsequence: "Cap raised; verification continued.",
        rejectConsequence: "Verification would have parked at the cap.",
        decision: "approved",
      },
      blocked: null,
      resolution: { outcome: "approved", at: "2026-09-24T15:10:00Z" },
    },
    {
      id: "attention-history-provider-rejected",
      kind: "approval",
      status: "rejected",
      severity: "warning",
      title: "External publish rejected",
      summary: "Publishing the draft summary externally was declined.",
      whatHappened: "An external-action request to publish the draft summary was rejected.",
      whyNeeded: "Historical record — no action remains.",
      inactionConsequence: "None; the draft stayed internal.",
      createdAt: "2026-09-24T11:00:00Z",
      updatedAt: "2026-09-24T11:20:00Z",
      source: "policy",
      destination: "logs",
      approval: {
        id: "appr-history-external",
        type: "external-action",
        requestedAction: "Publish the draft summary to the shared channel.",
        reason: "Draft contained unverified provider claims.",
        requester: "OCG policy gate",
        requestedAt: "2026-09-24T11:00:00Z",
        approveConsequence: "Draft would have been published.",
        rejectConsequence: "Draft stayed internal for another review pass.",
        decision: "rejected",
      },
      blocked: null,
      resolution: { outcome: "rejected", at: "2026-09-24T11:20:00Z", note: "Declined: unverified claims." },
    },
    {
      id: "attention-history-config-resolved",
      kind: "configuration",
      status: "resolved",
      severity: "info",
      title: "Source-control connection configured",
      summary: "Optional source-control step completed during setup.",
      whatHappened: "The optional source-control connection finished configuring.",
      whyNeeded: "Historical record — no action remains.",
      inactionConsequence: "None; already resolved.",
      createdAt: "2026-09-23T16:00:00Z",
      updatedAt: "2026-09-23T16:05:00Z",
      source: "configuration",
      destination: "settings",
      approval: null,
      blocked: null,
      resolution: { outcome: "resolved", at: "2026-09-23T16:05:00Z" },
    },
  ];
}

function overviewApprovals(): AttentionItem[] {
  return [
    {
      id: "attention-approval-spend",
      kind: "budget",
      status: "pending",
      severity: "high",
      title: "Approve $8 spend increase for consolidation",
      summary: "Wave 5 verification needs headroom beyond the $25 cap.",
      whatHappened: "Mission \"Consolidate OCG frontend architecture\" is approaching its spend cap with verification still queued.",
      whyNeeded: "Only you can authorize spend beyond the cap. OCG will not start Wave 5 until you decide.",
      inactionConsequence: "Wave 5 stays queued; verification and release gates never start.",
      createdAt: "2026-09-25T09:10:00Z",
      updatedAt: "2026-09-25T09:10:00Z",
      source: "policy",
      destination: "mission-control",
      missionId: "design-pwa-shell",
      missionTitle: "Consolidate OCG frontend architecture",
      approval: {
        id: "appr-spend-consolidation",
        type: "spend-increase",
        requestedAction: "Raise the Mission spend cap from $25 to $33.",
        reason: "Wave 5 verification and the release gate need roughly $8 of headroom at current burn.",
        requester: "OCG policy gate",
        missionId: "design-pwa-shell",
        missionTitle: "Consolidate OCG frontend architecture",
        requestedAt: "2026-09-25T09:10:00Z",
        estimatedImpact: "Verification and release gates run to completion; ledger stays the source of spend truth.",
        requestedSpendMicros: 8_000_000,
        approveConsequence: "Cap rises to $33 and Wave 5 starts.",
        rejectConsequence: "Mission parks at the cap; verification stays queued.",
        decision: "pending",
      },
      blocked: null,
      resolution: null,
    },
    {
      id: "attention-approval-retry",
      kind: "retry",
      status: "pending",
      severity: "warning",
      title: "Escalate ledger retry to Sol?",
      summary: "Ledger context failed once; a costlier model is proposed for retry 3.",
      whatHappened: "Task \"Connect Ledger context\" failed on attempt 1 (provider timeout) and is running attempt 2.",
      whyNeeded: "Confirm whether a third attempt may escalate to the costlier Sol model, or hold at the current model.",
      inactionConsequence: "Attempt 2 continues; a further failure re-surfaces without escalation.",
      createdAt: "2026-09-25T09:12:00Z",
      updatedAt: "2026-09-25T09:12:00Z",
      source: "execution",
      destination: "mission-control",
      missionId: "design-pwa-shell",
      missionTitle: "Consolidate OCG frontend architecture",
      taskId: "resource-ledger",
      taskTitle: "Connect Ledger context",
      approval: {
        id: "appr-retry-ledger",
        type: "retry-escalation",
        requestedAction: "Allow attempt 3 on Sol if attempt 2 fails.",
        reason: "Two timeouts suggest the current model is flaky for this task shape.",
        requester: "OCG execution gate",
        missionId: "design-pwa-shell",
        missionTitle: "Consolidate OCG frontend architecture",
        taskId: "resource-ledger",
        taskTitle: "Connect Ledger context",
        requestedAt: "2026-09-25T09:12:00Z",
        estimatedImpact: "One costlier attempt; success unblocks the integration gate.",
        requestedProvider: "Command Code",
        requestedModel: "Sol",
        approveConsequence: "Attempt 3 may use Sol on failure.",
        rejectConsequence: "Retries stay on the current model only.",
        decision: "pending",
      },
      blocked: null,
      resolution: null,
    },
    {
      id: "attention-approval-launch",
      kind: "approval",
      status: "pending",
      severity: "warning",
      title: "Approve Mission launch: Deploy readiness",
      summary: "Preflight passed; launch needs an explicit go-ahead.",
      whatHappened: "Mission \"Deploy readiness\" finished preflight and waits at the launch gate.",
      whyNeeded: "Launching starts provider calls. OCG holds here until you approve.",
      inactionConsequence: "The Mission stays queued; no provider calls start.",
      createdAt: DECISION_AT,
      updatedAt: DECISION_AT,
      source: "mission",
      destination: "mission-control",
      missionId: "mission-deploy",
      missionTitle: "Deploy readiness",
      approval: {
        id: "appr-launch-deploy",
        type: "mission-launch",
        requestedAction: "Launch Mission \"Deploy readiness\".",
        reason: "Preflight checks passed; rollout tasks are queued.",
        requester: "OCG planner",
        missionId: "mission-deploy",
        missionTitle: "Deploy readiness",
        requestedAt: DECISION_AT,
        estimatedImpact: "Rollout tasks start against the active profile.",
        approveConsequence: "Mission starts; workers are assigned.",
        rejectConsequence: "Mission stays queued until relaunched.",
        decision: "pending",
      },
      blocked: null,
      resolution: null,
    },
    {
      id: "attention-runtime-inspect",
      kind: "runtime-failure",
      status: "pending",
      severity: "critical",
      title: "Build worker reported a runtime failure",
      summary: "Builder invocation failed; inspect the evidence in Logs.",
      whatHappened: "The Build worker reported a runtime failure while connecting ledger context.",
      whyNeeded: "Confirm whether this is transient (retry) or needs reassignment before more budget burns.",
      inactionConsequence: "The failure keeps blocking downstream waves until acknowledged.",
      createdAt: "2026-09-25T09:15:00Z",
      updatedAt: "2026-09-25T09:15:00Z",
      source: "runtime",
      destination: "logs",
      missionId: "design-pwa-shell",
      missionTitle: "Consolidate OCG frontend architecture",
      taskId: "resource-ledger",
      taskTitle: "Connect Ledger context",
      approval: null,
      blocked: null,
      resolution: null,
    },
  ];
}

/** Fixture queue per scenario. Calm carries history only — zero unresolved. */
export function createAttentionQueue(scenario: ScenarioId): AttentionQueue {
  if (scenario === "attention-calm") {
    return { approvals: [], history: [history()[2]!] };
  }
  if (scenario === "attention-overview") {
    return { approvals: overviewApprovals(), history: history() };
  }
  return { approvals: [], history: [] };
}
