/**
 * Deterministic Resource Ledger fixture.
 *
 * The `resource-ledger` scenario exercises every shape the inspector must
 * render: multiple Missions and tasks, a Lead plus workers, arbitrary
 * providers, the same model on different providers, variants, component
 * diversity, heavy cache reuse, missing reasoning, known/unavailable/
 * explicit-zero cost, every usage authority and attribution confidence, and
 * every reconciliation status. No randomness is used.
 */

import type {
  AttributionConfidence,
  CostProvenance,
  LedgerCallStatus,
  LedgerRole,
  LedgerUsage,
  ReconciliationStatus,
  ResourceLedger,
  ResourceLedgerEntry,
  UsageAuthority,
} from "./types";
import type { ScenarioId } from "../runtime/runtime-types";

const BASE_MS = Date.parse("2026-03-04T09:00:00.000Z");

type EntryInput = {
  id: string;
  minutes: number;
  seconds?: number;
  sessionId?: string | null;
  invocationId?: string | null;
  durationMs?: number | null;
  latencyMs?: number | null;
  ttftMs?: number | null;
  missionId: string;
  missionLabel: string;
  taskId: string;
  taskLabel: string;
  workerId: string;
  workerLabel: string;
  role: LedgerRole;
  provider: string;
  model: string;
  variant?: string | null;
  callIndex: number;
  attempt?: number;
  status?: LedgerCallStatus;
  usage?: LedgerUsage | null;
  usageAuthority: UsageAuthority;
  costMicros?: number | null;
  costProvenance?: CostProvenance;
  attributionConfidence?: AttributionConfidence;
  attributedMissionId?: string | null;
  attributedTaskId?: string | null;
  reconciliation?: ReconciliationStatus;
  note?: string | null;
};

function record(input: EntryInput): ResourceLedgerEntry {
  const elapsedMs = input.minutes * 60_000 + (input.seconds ?? 0) * 1000;
  const timestamp = new Date(BASE_MS + elapsedMs).toISOString();
  const hasTiming = input.durationMs !== undefined && input.durationMs !== null;
  const costProvided = input.costMicros !== undefined && input.costMicros !== null;
  return {
    id: input.id,
    timestamp,
    startedAt: hasTiming ? timestamp : null,
    finishedAt: !hasTiming
      ? null
      : new Date(Date.parse(timestamp) + (input.durationMs ?? 0)).toISOString(),
    sessionId: input.sessionId ?? null,
    invocationId: input.invocationId ?? input.id,
    elapsedMs,
    durationMs: input.durationMs ?? null,
    latencyMs: input.latencyMs ?? null,
    ttftMs: input.ttftMs ?? null,
    missionId: input.missionId,
    missionLabel: input.missionLabel,
    taskId: input.taskId,
    taskLabel: input.taskLabel,
    workerId: input.workerId,
    workerLabel: input.workerLabel,
    role: input.role,
    provider: input.provider,
    model: input.model,
    variant: input.variant ?? null,
    callIndex: input.callIndex,
    attempt: input.attempt ?? 1,
    status: input.status ?? "success",
    usage: input.usage ?? null,
    usageAuthority: input.usageAuthority,
    costMicros: input.costMicros ?? null,
    costProvenance: input.costProvenance ?? (costProvided ? "reported" : "unavailable"),
    attributionConfidence: input.attributionConfidence ?? "exact",
    attributedMissionId: input.attributedMissionId ?? input.missionId,
    attributedTaskId: input.attributedTaskId ?? input.taskId,
    reconciliation: input.reconciliation ?? "reconciled",
    note: input.note ?? null,
  };
}

const RUNTIME = { id: "mission-runtime", label: "Durable mission runtime" } as const;
const LEDGER = { id: "mission-ledger", label: "Resource ledger inspector" } as const;
const DEPLOY = { id: "mission-deploy", label: "Deploy readiness" } as const;

const LEAD = {
  workerId: "lead",
  workerLabel: "Lead-Mid",
  role: "lead" as const,
  provider: "Command Code",
  model: "Muse Spark 1.3 Contributor",
  variant: "mid" as string | null,
};

const ENTRIES: ResourceLedgerEntry[] = [
  // Mission 1 — Durable mission runtime.
  record({
    ...LEAD,
    id: "rl-001",
    minutes: 0,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "scope",
    taskLabel: "Scope runtime contract",
    callIndex: 1,
    sessionId: "session-runtime",
    invocationId: "invocation-rl-001",
    durationMs: 820,
    latencyMs: 640,
    ttftMs: 160,
    usage: { freshInput: 840, cacheRead: 2100, cacheWrite: 300, output: 260 },
    usageAuthority: "reportedCall",
    costMicros: 18_400,
    costProvenance: "reported",
  }),
  record({
    id: "rl-002",
    minutes: 3,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "scope",
    taskLabel: "Scope runtime contract",
    workerId: "explore",
    workerLabel: "Explore",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "standard",
    callIndex: 1,
    usage: { freshInput: 1200, cacheRead: 0, cacheWrite: 420, output: 380 },
    usageAuthority: "reconciled",
    costMicros: 9_000,
    costProvenance: "stored",
  }),
  record({
    id: "rl-003",
    minutes: 7,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "build",
    taskLabel: "Implement runtime boundary",
    workerId: "explore",
    workerLabel: "Explore",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "standard",
    callIndex: 2,
    usage: { freshInput: 160, cacheRead: 5400, cacheWrite: 0, output: 220 },
    usageAuthority: "reconciled",
    // Explicit zero: the call was known to be free, not unknown.
    costMicros: 0,
    costProvenance: "reported",
    attributionConfidence: "inferred",
    attributedTaskId: "scope",
    reconciliation: "pending",
  }),
  record({
    id: "rl-004",
    minutes: 11,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "build",
    taskLabel: "Implement runtime boundary",
    workerId: "explore-deep",
    workerLabel: "Explore Deep",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "deep",
    callIndex: 1,
    usage: { freshInput: 900, cacheRead: 3000, output: 410, reasoning: 220 },
    usageAuthority: "reportedCall",
    costMicros: 22_000,
    costProvenance: "estimated",
  }),
  record({
    id: "rl-005",
    minutes: 15,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "build",
    taskLabel: "Implement runtime boundary",
    workerId: "build",
    workerLabel: "Builder",
    role: "worker",
    provider: "GOAT",
    model: "Muse Spark 1.3 Contributor",
    variant: "standard",
    callIndex: 1,
    usage: { freshInput: 1500, cacheWrite: 600, output: 500 },
    usageAuthority: "fallback",
    costMicros: null,
    costProvenance: "unavailable",
    reconciliation: "unknown",
  }),
  record({
    id: "rl-006",
    minutes: 18,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "build",
    taskLabel: "Implement runtime boundary",
    workerId: "build",
    workerLabel: "Builder",
    role: "worker",
    provider: "GOAT",
    model: "Muse Spark 1.3 Contributor",
    variant: "standard",
    callIndex: 2,
    attempt: 2,
    status: "retrying",
    usage: { freshInput: 700, cacheRead: 1800, output: 120 },
    usageAuthority: "estimated",
    costMicros: 12_000,
    costProvenance: "estimated",
    attributionConfidence: "inferred",
    reconciliation: "mismatch",
    note: "Transient provider error; retry scheduled.",
  }),
  record({
    id: "rl-007",
    minutes: 20,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "build",
    taskLabel: "Implement runtime boundary",
    workerId: "build",
    workerLabel: "Builder",
    role: "worker",
    provider: "GOAT",
    model: "Muse Spark 1.3 Contributor",
    variant: "standard",
    callIndex: 3,
    attempt: 3,
    usage: { freshInput: 240, cacheRead: 4200, cacheWrite: 0, output: 360 },
    usageAuthority: "reconciled",
    costMicros: 8_000,
    costProvenance: "stored",
    note: "Succeeded on retry after the cache warmed.",
  }),
  record({
    id: "rl-008",
    minutes: 24,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "verify",
    taskLabel: "Verify parallel workers",
    workerId: "verify",
    workerLabel: "Verifier",
    role: "worker",
    provider: "OpenCode Zen",
    model: "Muse Spark 1.3 Contributor Free",
    variant: null,
    callIndex: 1,
    usage: { freshInput: 600, output: 140 },
    usageAuthority: "reportedCall",
    costMicros: 4_000,
    costProvenance: "reported",
  }),
  record({
    ...LEAD,
    id: "rl-009",
    minutes: 28,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "verify",
    taskLabel: "Verify parallel workers",
    callIndex: 2,
    usage: { freshInput: 300, cacheRead: 5200, output: 180, reasoning: 90 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
    note: "Lead call served almost entirely from cache.",
  }),
  record({
    id: "rl-010",
    minutes: 33,
    missionId: RUNTIME.id,
    missionLabel: RUNTIME.label,
    taskId: "verify",
    taskLabel: "Verify parallel workers",
    workerId: "docs",
    workerLabel: "Docs",
    role: "worker",
    provider: "Local Runtime",
    model: "DeepSeek V4.1 Flash",
    variant: "low",
    callIndex: 1,
    usage: { freshInput: 480, output: 260 },
    usageAuthority: "estimated",
    costMicros: 3_000,
    costProvenance: "estimated",
    attributionConfidence: "unknown",
    attributedMissionId: null,
    attributedTaskId: null,
    reconciliation: "pending",
    note: "Timestamp-only attribution; owning Mission is unknown.",
  }),

  // Mission 2 — Resource ledger inspector.
  record({
    ...LEAD,
    id: "rl-011",
    minutes: 36,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "model",
    taskLabel: "Normalize ledger model",
    callIndex: 1,
    usage: { freshInput: 950, cacheRead: 1600, cacheWrite: 260, output: 300, reasoning: 140 },
    usageAuthority: "reportedCall",
    costMicros: 21_000,
    costProvenance: "reported",
  }),
  record({
    id: "rl-012",
    minutes: 40,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "model",
    taskLabel: "Normalize ledger model",
    workerId: "budget",
    workerLabel: "Budget Scout",
    role: "worker",
    provider: "GOAT",
    model: "DeepSeek V4.1 Flash",
    variant: "standard",
    callIndex: 1,
    usage: { freshInput: 1100, output: 320 },
    usageAuthority: "fallback",
    costMicros: null,
    costProvenance: "unavailable",
    attributionConfidence: "fallback",
    attributedTaskId: null,
    reconciliation: "unknown",
  }),
  record({
    id: "rl-013",
    minutes: 44,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "model",
    taskLabel: "Normalize ledger model",
    workerId: "explore-deep",
    workerLabel: "Explore Deep",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "deep",
    callIndex: 2,
    usage: { freshInput: 200, cacheRead: 6200, output: 240 },
    usageAuthority: "reconciled",
    costMicros: 5_000,
    costProvenance: "stored",
  }),
  record({
    id: "rl-014",
    minutes: 48,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "model",
    taskLabel: "Normalize ledger model",
    workerId: "explore",
    workerLabel: "Explore",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "standard",
    callIndex: 3,
    usage: { freshInput: 150, cacheRead: 4800, cacheWrite: 0, output: 190 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
    attributionConfidence: "inferred",
    reconciliation: "pending",
  }),
  record({
    id: "rl-015",
    minutes: 52,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "chart",
    taskLabel: "Chart component traffic",
    workerId: "build",
    workerLabel: "Builder",
    role: "worker",
    provider: "GOAT",
    model: "Muse Spark 1.3 Contributor",
    variant: "standard",
    callIndex: 1,
    usage: { freshInput: 1300, cacheWrite: 500, output: 420, reasoning: 260 },
    usageAuthority: "reportedCall",
    costMicros: 26_000,
    costProvenance: "estimated",
  }),
  record({
    id: "rl-016",
    minutes: 56,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "chart",
    taskLabel: "Chart component traffic",
    workerId: "verify",
    workerLabel: "Verifier",
    role: "worker",
    provider: "OpenCode Zen",
    model: "Muse Spark 1.3 Contributor Free",
    variant: null,
    callIndex: 1,
    status: "failure",
    usage: { freshInput: 500, output: 0 },
    usageAuthority: "estimated",
    costMicros: 2_000,
    costProvenance: "estimated",
    reconciliation: "mismatch",
    note: "Chart assertion failed; usage was still billed.",
  }),
  record({
    id: "rl-017",
    minutes: 58,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "chart",
    taskLabel: "Chart component traffic",
    workerId: "verify",
    workerLabel: "Verifier",
    role: "worker",
    provider: "OpenCode Zen",
    model: "Muse Spark 1.3 Contributor Free",
    variant: null,
    callIndex: 2,
    attempt: 2,
    usage: { freshInput: 260, cacheRead: 3100, output: 150 },
    usageAuthority: "reconciled",
    costMicros: 3_500,
    costProvenance: "stored",
    attributionConfidence: "inferred",
  }),
  record({
    id: "rl-018",
    minutes: 62,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "docs",
    taskLabel: "Document provenance",
    workerId: "docs",
    workerLabel: "Docs",
    role: "worker",
    provider: "Local Runtime",
    model: "DeepSeek V4.1 Flash",
    variant: "low",
    callIndex: 1,
    usage: { freshInput: 700, cacheRead: 900, output: 340 },
    usageAuthority: "fallback",
    costMicros: 0,
    costProvenance: "reported",
    attributionConfidence: "unknown",
    reconciliation: "notApplicable",
  }),
  record({
    ...LEAD,
    id: "rl-019",
    minutes: 66,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "docs",
    taskLabel: "Document provenance",
    callIndex: 2,
    usage: { freshInput: 420, cacheRead: 3000, output: 210, reasoning: 130 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
  }),
  record({
    id: "rl-020",
    minutes: 70,
    missionId: LEDGER.id,
    missionLabel: LEDGER.label,
    taskId: "docs",
    taskLabel: "Document provenance",
    workerId: "budget",
    workerLabel: "Budget Scout",
    role: "worker",
    provider: "GOAT",
    model: "DeepSeek V4.1 Flash",
    variant: "standard",
    callIndex: 2,
    usage: { freshInput: 800, cacheRead: 1200, output: 280 },
    usageAuthority: "reportedCall",
    costMicros: 7_000,
    costProvenance: "reported",
  }),

  // Mission 3 — Deploy readiness.
  record({
    ...LEAD,
    id: "rl-021",
    minutes: 76,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "probe",
    taskLabel: "Probe provider reachability",
    callIndex: 1,
    usage: { freshInput: 880, cacheRead: 2400, cacheWrite: 320, output: 290, reasoning: 120 },
    usageAuthority: "reportedCall",
    costMicros: 24_000,
    costProvenance: "reported",
  }),
  record({
    id: "rl-022",
    minutes: 82,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "probe",
    taskLabel: "Probe provider reachability",
    workerId: "explore",
    workerLabel: "Explore",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "standard",
    callIndex: 4,
    usage: { freshInput: 180, cacheRead: 5600, output: 210 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
    attributionConfidence: "inferred",
    reconciliation: "pending",
  }),
  record({
    id: "rl-023",
    minutes: 88,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "probe",
    taskLabel: "Probe provider reachability",
    workerId: "debug",
    workerLabel: "Debugger",
    role: "worker",
    provider: "Anthropic Direct",
    model: "DeepSeek V4.1 Flash",
    variant: "high",
    callIndex: 1,
    usage: { freshInput: 1400, cacheWrite: 700, output: 460, reasoning: 340 },
    usageAuthority: "fallback",
    costMicros: null,
    costProvenance: "unavailable",
    reconciliation: "unknown",
  }),
  record({
    id: "rl-024",
    minutes: 92,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "probe",
    taskLabel: "Probe provider reachability",
    workerId: "debug",
    workerLabel: "Debugger",
    role: "worker",
    provider: "Anthropic Direct",
    model: "DeepSeek V4.1 Flash",
    variant: "high",
    callIndex: 2,
    attempt: 2,
    status: "retrying",
    usage: { freshInput: 620, cacheRead: 2600, output: 110 },
    usageAuthority: "estimated",
    costMicros: 9_000,
    costProvenance: "estimated",
    attributionConfidence: "inferred",
    reconciliation: "mismatch",
  }),
  record({
    id: "rl-025",
    minutes: 96,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "probe",
    taskLabel: "Probe provider reachability",
    workerId: "debug",
    workerLabel: "Debugger",
    role: "worker",
    provider: "Anthropic Direct",
    model: "DeepSeek V4.1 Flash",
    variant: "high",
    callIndex: 3,
    attempt: 3,
    usage: { freshInput: 220, cacheRead: 5100, cacheWrite: 0, output: 330 },
    usageAuthority: "reconciled",
    costMicros: 11_000,
    costProvenance: "stored",
  }),
  record({
    id: "rl-026",
    minutes: 102,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "verify",
    workerLabel: "Verifier",
    role: "worker",
    provider: "OpenCode Zen",
    model: "Muse Spark 1.3 Contributor Free",
    variant: null,
    callIndex: 3,
    usage: { freshInput: 540, output: 160 },
    usageAuthority: "reportedCall",
    costMicros: 3_000,
    costProvenance: "reported",
  }),
  record({
    id: "rl-027",
    minutes: 108,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "build",
    workerLabel: "Builder",
    role: "worker",
    provider: "GOAT",
    model: "Muse Spark 1.3 Contributor",
    variant: "standard",
    callIndex: 2,
    usage: { freshInput: 1700, cacheRead: 800, cacheWrite: 640, output: 520 },
    usageAuthority: "reportedCall",
    costMicros: 23_000,
    costProvenance: "reported",
  }),
  record({
    id: "rl-028",
    minutes: 115,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "docs",
    workerLabel: "Docs",
    role: "worker",
    provider: "Local Runtime",
    model: "DeepSeek V4.1 Flash",
    variant: "low",
    callIndex: 2,
    status: "failure",
    usage: { freshInput: 300, output: 0 },
    usageAuthority: "fallback",
    costMicros: null,
    costProvenance: "unavailable",
    attributionConfidence: "fallback",
    attributedTaskId: null,
    reconciliation: "notApplicable",
  }),
  record({
    id: "rl-029",
    minutes: 120,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "docs",
    workerLabel: "Docs",
    role: "worker",
    provider: "Local Runtime",
    model: "DeepSeek V4.1 Flash",
    variant: "low",
    callIndex: 3,
    attempt: 2,
    usage: { freshInput: 120, cacheRead: 3900, output: 140 },
    usageAuthority: "reconciled",
    costMicros: 2_500,
    costProvenance: "stored",
    attributionConfidence: "unknown",
    reconciliation: "partial",
  }),
  record({
    ...LEAD,
    id: "rl-030",
    minutes: 128,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    callIndex: 2,
    usage: { freshInput: 260, cacheRead: 4400, output: 200, reasoning: 110 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
  }),
  record({
    id: "rl-031",
    minutes: 134,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "budget",
    workerLabel: "Budget Scout",
    role: "worker",
    provider: "GOAT",
    model: "DeepSeek V4.1 Flash",
    variant: "standard",
    callIndex: 3,
    usage: { freshInput: 1000, cacheRead: 1500, cacheWrite: 400, output: 300 },
    usageAuthority: "reportedCall",
    costMicros: 6_000,
    costProvenance: "reported",
  }),
  record({
    id: "rl-032",
    minutes: 140,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "explore",
    workerLabel: "Explore",
    role: "worker",
    provider: "OpenCode Go",
    model: "Space Bunny Free",
    variant: "standard",
    callIndex: 5,
    usage: { freshInput: 90, cacheRead: 7200, output: 180 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
    attributionConfidence: "inferred",
    reconciliation: "pending",
  }),
  record({
    id: "rl-033",
    minutes: 145,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    workerId: "debug",
    workerLabel: "Debugger",
    role: "worker",
    provider: "Anthropic Direct",
    model: "DeepSeek V4.1 Flash",
    variant: "high",
    callIndex: 4,
    usage: { freshInput: 460, cacheRead: 2200, output: 240, reasoning: 150 },
    usageAuthority: "reconciled",
    costMicros: 12_000,
    costProvenance: "estimated",
  }),
  record({
    ...LEAD,
    id: "rl-034",
    minutes: 150,
    missionId: DEPLOY.id,
    missionLabel: DEPLOY.label,
    taskId: "rollout",
    taskLabel: "Prepare rollout",
    callIndex: 3,
    usage: { freshInput: 340, cacheRead: 3600, output: 220, reasoning: 100 },
    usageAuthority: "reconciled",
    costMicros: 0,
    costProvenance: "reported",
  }),
];

/**
 * Returns the rich ledger only for the dedicated scenario. Other scenarios
 * carry `null` so the inspector shows an explicit empty state instead of
 * pretending every workspace has a ledger.
 */
export function createResourceLedgerFixture(scenario: ScenarioId): ResourceLedger | null {
  if (scenario !== "resource-ledger") return null;
  return {
    generatedAt: new Date(BASE_MS + 150 * 60_000).toISOString(),
    entries: ENTRIES.map((entry) => ({
      ...entry,
      usage: entry.usage ? { ...entry.usage } : null,
    })),
  };
}
