---
"$schema": https://opencode.ai/config.json
agent:
  build:
    disable: true
  plan:
    disable: true
  general:
    disable: true
  explore:
    disable: true
  scout:
    disable: true
keybinds:
  agent_cycle: shift+tab
  agent_cycle_reverse: tab
