/**
 * Normalized resource-ledger domain.
 *
 * This module is deliberately presentation-free. It owns the shape of a single
 * provider call as it appears in the Resource Ledger Inspector: usage split into
 * explicit components, cost with an explicit provenance, how usage was
 * authorized, how confidently the call was attributed to a Mission/task, and
 * whether the call reconciled against the durable ledger.
 *
 * Missing data is always `null` (rendered as `—`), never a fabricated zero.
 * Token counts are integers; cost is stored as integer micro-units of USD.
 */

export type UsageComponent =
  | "freshInput"
  | "cacheRead"
  | "cacheWrite"
  | "output"
  | "reasoning";

export const USAGE_COMPONENTS: readonly UsageComponent[] = [
  "freshInput",
  "cacheRead",
  "cacheWrite",
  "output",
  "reasoning",
];

export const USAGE_COMPONENT_LABEL: Record<UsageComponent, string> = {
  freshInput: "Fresh input",
  cacheRead: "Cache read",
  cacheWrite: "Cache write",
  output: "Output",
  reasoning: "Reasoning",
};

export const USAGE_COMPONENT_DEFINITION: Record<UsageComponent, string> = {
  freshInput: "Prompt tokens that were not served from cache.",
  cacheRead: "Prompt tokens served from a provider cache instead of being reprocessed.",
  cacheWrite: "Prompt tokens written into a provider cache for later calls.",
  output: "Tokens generated by the model for this call.",
  reasoning: "Tokens attributed to hidden reasoning or thinking, when the provider reports them.",
};

/** Where a cost number came from. `unavailable` means no cost was observed. */
export type CostProvenance = "reported" | "stored" | "estimated" | "unavailable";

export const COST_PROVENANCES: readonly CostProvenance[] = [
  "reported",
  "stored",
  "estimated",
  "unavailable",
];

export const COST_PROVENANCE_LABEL: Record<CostProvenance, string> = {
  reported: "Reported",
  stored: "Stored",
  estimated: "Estimated",
  unavailable: "Unavailable",
};

export const COST_PROVENANCE_DEFINITION: Record<CostProvenance, string> = {
  reported: "The provider reported an exact cost for this call.",
  stored: "Cost came from a locally stored price table rather than the provider.",
  estimated: "Cost was approximated from tokens and a known or assumed rate.",
  unavailable: "No cost was observed for this call; it is not zero.",
};

/** How the usage numbers were authorized for this call. */
export type UsageAuthority = "reportedCall" | "reconciled" | "fallback" | "estimated";

export const USAGE_AUTHORITIES: readonly UsageAuthority[] = [
  "reportedCall",
  "reconciled",
  "fallback",
  "estimated",
];

export const USAGE_AUTHORITY_LABEL: Record<UsageAuthority, string> = {
  reportedCall: "Reported call",
  reconciled: "Reconciled",
  fallback: "Fallback",
  estimated: "Estimated",
};

export const USAGE_AUTHORITY_DEFINITION: Record<UsageAuthority, string> = {
  reportedCall: "Usage came directly from the provider response for this call.",
  reconciled: "Usage was derived from durable ledger totals after reconciliation.",
  fallback: "Usage came from a weaker fallback source because the provider did not report it.",
  estimated: "Usage was estimated locally from tokens or streaming deltas.",
};

/** Confidence that this call belongs to the Mission/task it is grouped under. */
export type AttributionConfidence = "exact" | "inferred" | "fallback" | "unknown";

export const ATTRIBUTION_CONFIDENCES: readonly AttributionConfidence[] = [
  "exact",
  "inferred",
  "fallback",
  "unknown",
];

export const ATTRIBUTION_CONFIDENCE_LABEL: Record<AttributionConfidence, string> = {
  exact: "Exact",
  inferred: "Inferred",
  fallback: "Fallback",
  unknown: "Unknown",
};

export const ATTRIBUTION_CONFIDENCE_DEFINITION: Record<AttributionConfidence, string> = {
  exact: "The call carries an explicit Mission and task identifier.",
  inferred: "The Mission/task was inferred from worker, task ordering, or time window.",
  fallback: "Attribution fell back to the owning Mission because the task is not known.",
  unknown: "The call could not be attributed; it is surfaced as an unknown bucket.",
};

/** State of the reconciliation between observed calls and the durable ledger. */
export type ReconciliationStatus =
  | "reconciled"
  | "partial"
  | "pending"
  | "mismatch"
  | "notApplicable"
  | "unknown";

export const RECONCILIATION_STATUSES: readonly ReconciliationStatus[] = [
  "reconciled",
  "partial",
  "pending",
  "mismatch",
  "notApplicable",
  "unknown",
];

export const RECONCILIATION_LABEL: Record<ReconciliationStatus, string> = {
  reconciled: "Reconciled",
  partial: "Partial",
  pending: "Pending",
  mismatch: "Mismatch",
  notApplicable: "Not applicable",
  unknown: "Unknown",
};

export const RECONCILIATION_DEFINITION: Record<ReconciliationStatus, string> = {
  reconciled: "Observed call totals match the durable ledger for this scope.",
  partial: "Only part of the observed scope could be reconciled.",
  pending: "Reconciliation has not completed; the value may still change.",
  mismatch: "Observed and durable totals disagree and need operator review.",
  notApplicable: "Reconciliation does not apply to this call (for example, a free call).",
  unknown: "Reconciliation state was not reported.",
};

export type LedgerCallStatus = "success" | "failure" | "retrying";

export type LedgerRole = "lead" | "worker";

/** Token counts per component. A missing key means the component was not observed. */
export type LedgerUsage = Partial<Record<UsageComponent, number>>;

export type ResourceLedgerEntry = {
  id: string;
  /** ISO-8601 timestamp. */
  timestamp: string;
  startedAt: string | null;
  finishedAt: string | null;
  sessionId: string | null;
  invocationId: string | null;
  elapsedMs: number;
  durationMs: number | null;
  latencyMs: number | null;
  ttftMs: number | null;
  missionId: string;
  missionLabel: string;
  taskId: string;
  taskLabel: string;
  workerId: string;
  workerLabel: string;
  role: LedgerRole;
  provider: string;
  model: string;
  variant: string | null;
  /** 1-based sequence of this call within its worker/task. */
  callIndex: number;
  /** 1-based attempt; values greater than 1 are retries. */
  attempt: number;
  status: LedgerCallStatus;
  usage: LedgerUsage | null;
  usageAuthority: UsageAuthority;
  /** Integer micro-units of USD (1 USD = 1_000_000 micros). `null` is unavailable, not zero. */
  costMicros: number | null;
  costProvenance: CostProvenance;
  attributionConfidence: AttributionConfidence;
  attributedMissionId: string | null;
  attributedTaskId: string | null;
  reconciliation: ReconciliationStatus;
  note: string | null;
};

/** The full normalized ledger for a workspace. */
export type ResourceLedger = {
  generatedAt: string;
  entries: ResourceLedgerEntry[];
};

export type LedgerTab = "overview" | "ledger" | "attribution" | "providers" | "models";

export const LEDGER_TABS: readonly LedgerTab[] = [
  "overview",
  "ledger",
  "attribution",
  "providers",
  "models",
];

export const LEDGER_TAB_LABEL: Record<LedgerTab, string> = {
  overview: "Overview",
  ledger: "Ledger",
  attribution: "Attribution",
  providers: "Providers",
  models: "Models",
};

export type TimeWindow = "all" | "today" | "last15m" | "last1h" | "last6h" | "last24h" | "last7d";

export const TIME_WINDOWS: readonly TimeWindow[] = ["all", "today", "last15m", "last1h", "last6h", "last24h", "last7d"];

export const TIME_WINDOW_LABEL: Record<TimeWindow, string> = {
  all: "All time",
  today: "Today",
  last15m: "Last 15 minutes",
  last1h: "Last hour",
  last6h: "Last 6 hours",
  last24h: "Last 24 hours",
  last7d: "Last 7 days",
};

export const TIME_WINDOW_MS: Record<Exclude<TimeWindow, "all">, number> = {
  today: 24 * 60 * 60_000,
  last15m: 15 * 60_000,
  last1h: 60 * 60_000,
  last6h: 6 * 60 * 60_000,
  last24h: 24 * 60 * 60_000,
  last7d: 7 * 24 * 60 * 60_000,
};

export const ALL_FILTER_VALUE = "all";

export type LedgerFilter = {
  window: TimeWindow;
  missionId: string;
  workerId: string;
  provider: string;
  /** `provider\u0000model` key so the same model on different providers stays distinct. */
  modelKey: string;
};

export const DEFAULT_LEDGER_FILTER: LedgerFilter = {
  window: "all",
  missionId: ALL_FILTER_VALUE,
  workerId: ALL_FILTER_VALUE,
  provider: ALL_FILTER_VALUE,
  modelKey: ALL_FILTER_VALUE,
};

export type FilterOption = {
  value: string;
  label: string;
  detail?: string;
};

export type LedgerFilterOptions = {
  missions: FilterOption[];
  workers: FilterOption[];
  providers: FilterOption[];
  models: FilterOption[];
};

export type LedgerDimension =
  | "mission"
  | "task"
  | "worker"
  | "provider"
  | "model"
  | "modelVariant"
  | "attribution"
  | "reconciliation";

export const LEDGER_DIMENSIONS: readonly LedgerDimension[] = [
  "mission",
  "task",
  "worker",
  "provider",
  "model",
  "modelVariant",
  "attribution",
  "reconciliation",
];

export const LEDGER_DIMENSION_LABEL: Record<LedgerDimension, string> = {
  mission: "Mission",
  task: "Task",
  worker: "Worker",
  provider: "Provider",
  model: "Model",
  modelVariant: "Model + variant",
  attribution: "Attribution confidence",
  reconciliation: "Reconciliation",
};

export type LedgerSeriesKey = UsageComponent | "total";

export type LedgerSeriesDefinition = {
  key: LedgerSeriesKey;
  label: string;
  color: string;
};

/** Stable series order and colors for the traffic-over-time chart toggles. */
export const LEDGER_SERIES: readonly LedgerSeriesDefinition[] = [
  { key: "freshInput", label: USAGE_COMPONENT_LABEL.freshInput, color: "var(--chart-2)" },
  { key: "cacheRead", label: USAGE_COMPONENT_LABEL.cacheRead, color: "var(--chart-1)" },
  { key: "cacheWrite", label: USAGE_COMPONENT_LABEL.cacheWrite, color: "var(--chart-3)" },
  { key: "output", label: USAGE_COMPONENT_LABEL.output, color: "var(--chart-4)" },
  { key: "reasoning", label: USAGE_COMPONENT_LABEL.reasoning, color: "var(--chart-5)" },
  { key: "total", label: "Total", color: "var(--foreground)" },
];
